### ISSUE TITLE
Where are the roles?

### ISSUE THREAD

**Issue by tzabbi** [dschier-wtd/fedora-workstation#6]
Heyho,

did you deleted all roles?

Best Tom

**Comment by dschier-wtd** [comment]
Hey @tzabbi, nothing is deleted. :smiley: 

Check out https://github.com/dschier-wtd/fedora-workstation/blob/main/ansible/requirements.yml

**Comment by tzabbi** [comment]
Ahh thanks! I don't know this works in ansible^^
